
classnames66 = [
    ['metallic; artificial', 'nonmetallic; natural'],
    ['food-related', 'non-food-related'],
    ['animal-related', 'non-animal-related; artificial; inorganic'],
    ['textile', 'non-textile'],
    ['plant-related', 'non-plant-related'],
    ['house-related; furnishing-related',
    'non-house-related; non-furnishing-related; outdoors-related'],
    ['valuable; precious', 'non-valuable; inexpensive; cheap'],
    ['transportation; movement-related', 'non-transportation; movement-related'],
    ['body; people-related', 'non-body; people-related'],
    ['wood-related; brown', 'non-wood-related; non-brown'],
    ['electronics; technology', 'non-electronics; technology'],
    ['colorful; playful', 'monotone; dull'],
    ['outdoors', 'non-outdoors'],
    ['circular; round', 'non-circular; angular'],
    ['paper-related; flat', 'non-paper-related; bumpy'],
    ['hobby-related; game-related; playing-related',
    'non-hobby-related; non-game-related; non-playing-related'],
    ['tools-related; handheld; elongated',
    'non-tools-related; non-handheld; shortened'],
    ['fluid-related; drink-related', 'solid-related; non-fluid-related'],
    ['water-related', 'dry; non-water-related'],
    ['oriented; many; plenty', 'non-oriented; few; scarce'],
    ['powdery; earth-related; waste-related',
    'non-powdery; non-earth-related; non-waste-related'],
    ['white', 'black; dark'],
    ['coarse-scale pattern; many things', 'non-coarse-scalepattern; few; scarce'],
    ['red', 'non-red'],
    ['long; thin', 'short; thick'],
    ['weapon-related; war-related; dangerous',
    'non-weapon-related; non-war-related; peaceful'],
    ['black', 'non-black; white'],
    ['household-related', 'non-household-related'],
    ['feminine', 'non-feminine; masculine'],
    ['body-part-related', 'non-body-part-related'],
    ['tubular', 'non-tubular'],
    ['music-related; hearing-related; hobby-related; loud',
    'non-music-related; non-hearing-related; non-hobby-related; silent'],
    ['grid-related; grating-related', 'non-grid-related; non-grating-related'],
    ['repetitive; spiky', 'diverse; dull'],
    ['construction-related; craftsmanship-related; housework-related',
    'non-physical-work-related'],
    ['spherical; voluminous', 'angular; small'],
    ['string-related; stringy; curved', 'non-string-related; straight'],
    ['seating; standing; lying-related',
    'non-seating; non-standing; non-lying-related'],
    ['flying-related; sky-related', 'ground-related; non-flying-related'],
    ['bug-related; non-mammalian; disgusting',
    'non-bug-related; mammalian; pleasant'],
    ['transparent; shiny; crystalline', 'opaque; matte; frosted'],
    ['sand-colored', 'non-sand-colored'],
    ['green', 'non-green'],
    ['bathroom-related; wetness-related', 'non-bathroom-related; dry'],
    ['yellow', 'non-yellow'],
    ['heat-related; fire-related; light-related', 'cold-related; dark-related'],
    ['beams-related; mesh-related', 'non-beams-related; non-mesh-related'],
    ['foot-related; walking-related', 'non-foot-related; non-walking-related'],
    ['box-related; container', 'non-box-related; non-container'],
    ['stick-shaped; container', 'non-stick-shaped; non-container'],
    ['head-related', 'non-head-related'],
    ['upright; elongated; volumous', 'non-upright; short; small'],
    ['pointed; spiky', 'non-pointed; blunt'],
    ['child-related; toy-related; cute', 'mature; adult-like'],
    ['farm-related; historical', 'non-farm-related; contemporary'],
    ['seeing-related', 'non-seeing-related; blind'],
    ['medicine-related; health-related',
    'non-medicine-related; non-health-related'],
    ['sweet; dessert-related', 'non-sweet; non-dessert-related'],
    ['orange', 'non-orange'],
    ['thin; flat; wrapping', 'thick; bumpy; non-wrapping'],
    ['cylindrical; conical; cushioning', 'triangular; angular; hardening'],
    ['coldness-related; winter-related', 'warmness-related; non-winter-related '],
    ['measurement-related; numbers-related',
    'non-measurement-related; non-numerical'],
    ['fluffy; soft', 'non-fluffy; rough'],
    ['masculine', 'non-masculine; feminine'],
    ['fine-grained; pattern', 'non-fine-grained; plain']
]


# Alternatively, there is a 49 class version of the SPoSE dimensions
classnames49 = [
    ["made of metal / artificial / hard", "made of nonmetal / natural / soft"],
    ["food-related /eating-related / kitchen-related", "non-food-related / non-eating-related / non-kitchen-related"],
    ["animal-related / organic", "non-animal-related / artificial / inorganic"],
    ["clothing-related / fabric / covering", "non-clothing-related / non-fabric"],
    ["furniture-related / household-related / artifact", "non-furniture-related / non-household-related / outdoors-related"],
    ["plant-related / green", "non-plant-related / non-green"],
    ["outdoors-related", "indoors-related"],
    ["transportation / motorized / dynamic", "non-transportation / non-motorized / slow"],
    ["wood-related / brown", "non-wood-related / non-brown"],
    ["body part-related", "non-body-part-related"],
    ["colorful", "monotone"],
    ["valuable special occasion-related", "common / generic / non-valuable"],
    ["electronic / technology", "non-electronic / nature"],
    ["sport-related / recreation-related", "non-sport-related / non-recreation-related"],
    ["disc-shaped / round", "angular / confusing shapes / protruding"],
    ["tool-related", "non-tool-related"],
    ["many small things / coarse pattern", "smooth pattern / singular object"],
    ["paper-related / thin / flat / text-related", "non-paper-related / wide / textured / non-text-related"],
    ["fluid-related / drink-related", "solid-related / non-fluid-related / non-drink-related"],
    ["long / thin", "short / wide"],
    ["water-related / blue", "dry / non-blue / non-water-related"],
    ["powdery / fine-scale pattern", "singular object / smooth / large pieces"],
    ["red", "non-red"],
    ["feminine (stereotypically) / decorative", "masculine (stereotypically) / minimalist"],
    ["bathroom-related / sanitary", "non-bathroom-related / unsanitary"],
    ["black / noble", "unrefined / lowly"],
    ["weapon / danger-related / violence", "calming / nurturing / safety-related"],
    ["musical instrument-related / noise-related", "quiet / silence / non-musical-instrument-related"],
    ["sky-related / flying-related / floating-related", "non-sky-related / ground-related / non-flying-related"],
    ["spherical / ellipsoid / rounded / voluminous", "angular / spiky / sharp"],
    ["repetitive", "varied / disorganized"],
    ["flat / patterned", "bumpy / rough / disorganized"],
    ["white", "black"],
    ["thin / flat", "wide / rough / bumpy"],
    ["disgusting / bugs", "cute / pleasant / non-bugs"],
    ["string-related", "non-string-related"],
    ["arms/legs/skin-related", "non-skin-related"],
    ["shiny / tranparent", "muted / opaque"],
    ["construction-related / physical work-related", "non-physical-work-related"],
    ["fire-related / heat-related", "non-fire-related / cold-related"],
    ["head-related / face-related", "non-head-related / non-face-related"],
    ["beams-related", "non-beams-related"],
    ["eating-related / put things on top", "non-eating-related"],
    ["container-related / hollow", "solid / full / non-container-related"],
    ["child-related / toy-related", "non-child-related / mature"],
    ["medicine-related", "non-medicine-related"],
    ["has grating", "no grating"],
    ["handicraft-related", "non-handicraft-related"],
    ["cylindrical / conical", "triangular / angular / non-cylindrical / non-conical"]
]
